[package]
name = "absurd-smov-proxy"
authors = ["absurdprofit <nahtanjohn1l@gmail.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
futures-util = "0.3.30"
spin-sdk = "3.0.1"
url = "2.5.2"
urlencoding = "2.1.3"

[workspace]
