[package]
name = "smov-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
url = "2.2"
urlencoding = "2.1"
futures-util = "0.3"
async-stream = "0.3"