services:
  absurd-smov-proxy:
    build:
      args:
        - provenance=false
        - PLATFORM=wasi/wasm
      context: .
    image: absurd-smov-proxy
    container_name: absurd-smov-proxy
    ports:
      - "3000:80"
    runtime: io.containerd.spin.v2