services:
  absurd-smov-proxy:
    build:
      args:
        - BUILDPLATFORM=linux/amd64
      platforms:
        - wasi/wasm
      context: .
    image: absurd-smov-proxy
    container_name: absurd-smov-proxy
    ports:
      - "3000:80"
    runtime: io.containerd.spin.v2
    platform: wasi/wasm